---
codecov:
  require_ci_to_pass: yes
  branch: main
  strict_yaml_branch: main
  max_report_age: 1

coverage:
  precision: 3
  round: down
  range: "90...100"
  status:
    project:
      default:
        target: auto
        threshold: 2
        if_ci_failed: error

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: new
  require_changes: no

github_checks:
  annotations: no

fixes:
- "/home/runner/work/node-philomena/node-philomena/::"
