---
on:
  push:
    branches:
      - "*"
    tags:
      - "*"
name: ci

jobs:
  build:
    name: build/test/lint
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ["10", "12", "14", "15"]

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: install dependencies
      run: npm i

    - name: build
      run: npm run build

    - name: test
      run: |
        npm run test:ci
        bash <(curl -s https://codecov.io/bash) -n ${{ matrix.node-version }}

    # i think its more efficient to lint 3 times than to setup a new
    # environment just to lint
    - name: lint
      run: npm run lint

  docs:
    name: docs
    runs-on: ubuntu-20.04
    steps:
    - name: get ref name
      run: echo FOLDERNAME=${GITHUB_REF#refs/*/} >> $GITHUB_ENV

    - name: checkout code
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: "15"

    - name: install dependencies
      run: npm i

    - name: render docs
      run: npm run docs

    - name: deploy docs
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs
        CLEAN: false
