---
on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
name: ci

jobs:
  build:
    name: build/test/lint
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ["10", "12", "14", "15"]

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v1.2.1
      with:
        version: 5.13.1

    - name: install dependencies
      run: pnpm i

    - name: build
      run: pnpm run build

    - name: test
      run: |
        pnpm test
        bash <(curl -s https://codecov.io/bash) -f testresults.json

    # i think its more efficient to lint 3 times than to setup a new
    # environment just to lint
    - name: lint
      run: pnpm run lint
