---
on:
- push
- pull_request
name: ci

jobs:
  build:
    name: do the checks
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ["10", "12", "14", "15"]
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v1.2.1
      with:
        version: 5.13.1

    - name: install dependencies
      run: pnpm i

    - name: build
      run: pnpm run build

    - name: test
      run: |
        pnpm test
        bash <(curl -s https://codecov.io/bash) -f testresults.json

  docs:
    name: lint/docs
    runs-on: ubuntu-20.04
    steps:
    - name: get ref name
      run: echo FOLDERNAME=${GITHUB_REF#refs/*/} >> $GITHUB_ENV

    - name: checkout code
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: "15"

    - name: Setup pnpm
      uses: pnpm/action-setup@v1.2.1
      with:
        version: 5.13.1

    - name: install dependencies
      run: pnpm i

    - name: lint
      run: pnpm run lint

    - name: render docs
      run: npm run docs

    - name: deploy docs
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs
        CLEAN: false
