---
on:
  push:
    branches:
      - "*"
  pull_request:

name: ci

jobs:
  build:
    name: build/test/lint
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ["10", "12", "14", "15"]

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: install dependencies
      run: npm ci

    - name: build
      run: npm run build:ci

    - name: test
      run: |
        npm run test:ci
        bash <(curl -s https://codecov.io/bash) -n ${{ matrix.node-version }}

    # i think its more efficient to lint 3 times than to setup a new
    # environment just to lint
    - name: lint
      run: npm run lint:ci
