---
on:
  push:
    branches:
      - "*"
    tags:
      - "*"
name: ci

jobs:
  docs:
    name: docs
    runs-on: ubuntu-20.04
    steps:
    - name: get ref name
      run: echo FOLDERNAME=${GITHUB_REF#refs/*/} >> $GITHUB_ENV

    - name: checkout code
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: "15"

    - name: install dependencies
      run: npm ci

    - name: type check
      run: npx tsc --noEmit

    - name: render docs
      run: npm run docs

    - name: deploy docs
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs
        CLEAN: false
